name: README Auto Sync

on:
  push:
    branches: [main]
    paths:
      - links.json
      - README.tpl.md
      - CONTENT.md
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ctx:
    runs-on: ubuntu-latest
    outputs:
      concept_doi: ${{ steps.meta.outputs.concept_doi }}
    steps:
      - uses: actions/checkout@v4
      - id: meta
        shell: bash
        run: |
          val=$(jq -r '.zenodo_concept_doi // empty' links.json 2>/dev/null || echo "")
          echo "concept_doi=$val" >> "$GITHUB_OUTPUT"

  build:
    needs: ctx
    uses: JSunOfficial-arch/.github/.github/workflows/readme-sync.yml@main
    with:
      concept_doi: ${{ needs.ctx.outputs.concept_doi }}
