# .github/workflows/readme.yml  （在 anchor-registry 仓库里）
name: README Auto Sync

on:
  push:
    branches: [ main ]
    paths:
      - links.json
      - README.tpl.md
      - CONTENT.md
  workflow_dispatch:

# 调用方只读即可；写权限由被调用工作流里设置
permissions:
  contents: write

jobs:
  sync:
    uses: JSunOfficial-arch/.github/.github/workflows/readme-sync.yml@main
    secrets: inherit
