name: README Auto Sync

on:
  push:
    branches: [main]
    paths:
      - links.json
      - README.tpl.md
      - CONTENT.md
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: JSunOfficial-arch/.github/.github/workflows/readme-sync.yml@main
    with:
      concept_doi: ${{ fromJson(steps.ctx.outputs.data).zenodo_concept_doi }}
