name: README Auto Sync

on:
  push:
    branches: [ main ]
    paths:
      - links.json
      - README.tpl.md
      - CONTENT.md
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    uses: JSunOfficial-arch/.github/.github/workflows/readme-sync.yml@main
    with:
      concept_doi: 10.5281/zenodo.16778141
    secrets: inherit
